version: '3.3'

services:
  bot-vpn:
    build:
      context: .. # Контекст сборки — корень проекта
      dockerfile: docker/Dockerfile # Путь к Dockerfile
    container_name: bot-vpn
    env_file:
      - ../.env # Подключаем .env файл из корня проекта
    volumes:
      - ../.env:/../.env # Монтируем .env файл внутрь контейнера, если нужно
    ports:
      - "8080:8080" # Если ваше приложение использует HTTP-сервер, настройте порт
    environment:
      GO_ENV: production # Устанавливаем переменные окружения
    command: ["./main"] # Указываем, как запускать приложение
