version: '3.3'

services:
  bot-vpn:
    build:
      context: ..  # Контекст сборки — корень проекта
      dockerfile: docker/Dockerfile  # Путь к Dockerfile
    container_name: bot-vpn
    restart: always
    ports:
      - "8080:8080"  # Если приложение использует HTTP-сервер
    environment:
      - BOT_TOKEN=${BOT_TOKEN}
#      - DATABASE_URL=${DATABASE_URL}  # Укажите нужные переменные
      - GO_ENV=production
    command: ["./main"]  # Указываем, как запускать приложение
