name: Deploy to Server

on:
  push:
    branches:
      - main  # Запуск при пуше в main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy to server
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /root/VPN
            git reset --hard
            git pull origin main
            docker-compose down

            docker-compose -f docker/docker-compose.yml up --build -d \
              -e BOT_TOKEN=${{ secrets.BOT_TOKEN }} \
              -e API_URL=${{ secrets.API_URL }} \
              -e PORT=${{ secrets.PORT }} \
              -e POSTGRES_HOST=${{ secrets.POSTGRES_HOST }} \
              -e POSTGRES_NAME=${{ secrets.POSTGRES_NAME }} \
              -e POSTGRES_PASS=${{ secrets.POSTGRES_PASS }} \
              -e POSTGRES_PORT=${{ secrets.POSTGRES_PORT }} \
              -e POSTGRES_USER=${{ secrets.POSTGRES_USER }} \
              -e REDIS_ADDR=${{ secrets.REDIS_ADDR }} \
              -e REDIS_DB=${{ secrets.REDIS_DB }} \
              -e REDIS_PASS=${{ secrets.REDIS_PASS }} \
              -e SERVER_IP=${{ secrets.SERVER_IP }}
